// Auto-generated by @vetniva/load-test (GOAL-122).
// Senaryo: pos — Petshop POS
// Profil: pilot (10 VU, 2dk — pilot dogrulama)
// Bu dosya elle degistirilmemelidir; ureticiden gelir.

import { vetPost, check, jitterSleep, maskString, resolveDeep, resolvePath } from './shared.js';

export const options = {
  // Release raporu p95 ve p99 esiklerini degerlendirir.
  summaryTrendStats: ['min', 'med', 'avg', 'p(90)', 'p(95)', 'p(99)', 'max'],
  stages: [
    { duration: '15s', target: 10 },     // warm-up
    { duration: '2m', target: 10 }, // sustained
    { duration: '15s', target: 0 },                    // cool-down
  ],
  thresholds: {
    // k6 tarafinda hizli baseline; detayli kontrol TypeScript
    // tarafinda (evaluateScenario) yapilir.
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<2000'],
  },
  tags: { suite: 'vetniva-load-test' },
};

export default async function () {
  // step 1: create_sale_draft
  const res0 = vetPost(
    resolvePath("/api/v1/petshop/sales"),
    resolveDeep({
  "lines": [
    {
      "productId": "{productId}",
      "unit": "unit",
      "quantity": "1",
      "unitPrice": "100.00"
    }
  ],
  "customerOwnerId": "{ownerId}",
  "customerPatientId": "{patientId}",
  "paymentMethod": "cash",
  "paidAmount": "0"
}),
  );
  check(res0, {
    'create_sale_draft_status_201': (r) => r.status === 201,
    // Yetkili API cevabi PII icerebilir; test istemcisi bu cevabi tanisal
    // ciktilara yazmadan once maskeler. Bu kontrol maskeleme sozlesmesini
    // dogrular, yetkili kullaniciya gosterilen veriyi "sizinti" saymaz.
    'create_sale_draft_diagnostic_body_masked': (r) => !/[\\w.+-]+@[\\w-]+\\.[\\w.-]+|\\b[5-9]\\d{9}[0-9]\\b|\\b0?5\\d{9}\\b/.test(maskString(typeof r.body === 'string' ? r.body : '')),
  });
  jitterSleep(50, 200);

}
