// Auto-generated by @vetniva/load-test (GOAL-122).
// Senaryo: report — Temel finans raporu
// Profil: pilot (10 VU, 2dk — pilot dogrulama)
// Bu dosya elle degistirilmemelidir; ureticiden gelir.

import { vetGet, check, jitterSleep } from "./shared.js";

export const options = {
  vus: 10,
  duration: "2m",
  thresholds: {
    // k6 tarafinda hizli baseline; detayli kontrol TypeScript
    // tarafinda (evaluateScenario) yapilir.
    http_req_failed: ["rate<0.05"],
    http_req_duration: ["p(95)<2000"],
  },
  tags: { suite: "vetniva-load-test" },
};

export default async function () {
  // step 1: daily_report
  const res0 = vetGet("/api/v1/finance/reports/daily?date=today", undefined);
  check(res0, {
    daily_report_status_200: (r) => r.status === 200,
    daily_report_no_pii_leak: (r) =>
      !/[\\w.+-]+@[\\w-]+\\.[\\w.-]+|\\b[5-9]\\d{9}[0-9]\\b|\\b0?5\\d{9}\\b/.test(
        typeof r.body === "string" ? r.body : "",
      ),
  });
  jitterSleep(50, 200);
}
