/**
 * @file Permission spec — type union + hard-coded liste.
 * @module apps/api/common/permissions/permission-spec
 *
 * @description VetNiva izin kataloğunun runtime tür tanımı.
 * `docs/permissions/PERMISSION_CATALOG.yaml` dosyasındaki tüm
 * permission anahtarları burada hard-coded liste + TypeScript
 * string-literal union olarak tutulur. `pnpm docs:check` CI
 * kapısı YAML katalog ile bu liste arasında senkronizasyon sağlar.
 *
 * Format: `<domain>:<resource>:<action>` (ör. `clinic:owner:read`).
 * Toplam 156 permission (FAZ-1 + FAZ-6 tedarikçi/satın alma + FAZ-6 GOAL-067 stok uyarıları kapsamı).
 *
 * @since GOAL-002 (FAZ-0) yetki matrisi
 * @updated GOAL-012 (FAZ-1) RBAC ve izin motoru
 */

export const ACTOR_ROLES = [
  "SUPERADMIN",
  "OWNER",
  "VETERINARIAN",
  "STAFF",
  "PET_OWNER_PORTAL",
  "SYSTEM",
] as const;
export type ActorRole = (typeof ACTOR_ROLES)[number];

export const PERMISSIONS = [
  "common:notification:read",
  "common:notification:update",
  "common:notification:manage",
  "common:profile:read",
  "common:profile:update",
  "common:settings:read",
  "common:settings:update",
  "tenant:tenant:read",
  "tenant:tenant:create",
  "tenant:tenant:update",
  "tenant:tenant:archive",
  "branch:branch:read",
  "branch:branch:create",
  "branch:branch:update",
  "branch:branch:archive",
  "user:user:read",
  "user:user:invite",
  "user:user:update",
  "user:user:suspend",
  "user:user:assign_role",
  "role:role:read",
  "role:role:assign",
  "role:role:manage",
  "clinic:owner:read",
  "clinic:owner:create",
  "clinic:owner:update",
  "clinic:owner:archive",
  "clinic:owner:erase",
  "clinic:owner:export",
  "clinic:patient:read",
  "clinic:patient:create",
  "clinic:patient:update",
  "clinic:patient:archive",
  "clinic:patient:transfer",
  "clinic:patient:export",
  "clinic:appointment:read",
  "clinic:appointment:create",
  "clinic:appointment:update",
  "clinic:appointment:cancel",
  "clinic:appointment:complete",
  "clinic:appointment:export",
  "clinic:appointment:request",
  "clinic:examination:read",
  "clinic:examination:create",
  "clinic:examination:sign",
  "clinic:examination:amend",
  "clinic:examination:export",
  "clinic:soap:read",
  "clinic:soap:create",
  "clinic:soap:update",
  "clinic:soap:amend",
  "clinic:vaccination:read",
  "clinic:vaccination:create",
  "clinic:vaccination:amend",
  "clinic:vaccination:export",
  "clinic:prescription:read",
  "clinic:prescription:create",
  "clinic:prescription:dispense",
  "clinic:prescription:cancel",
  "clinic:prescription:amend",
  "clinic:prescription:export",
  "clinic:surgery:read",
  "clinic:surgery:create",
  "clinic:surgery:schedule",
  "clinic:surgery:start",
  "clinic:surgery:complete",
  "clinic:surgery:cancel",
  "clinic:surgery:amend",
  "clinic:surgery:export",
  "clinic:consent:sign",
  "clinic:consent:read",
  "clinic:anesthesia:read",
  "clinic:anesthesia:create",
  "clinic:anesthesia:update",
  "clinic:anesthesia:export",
  "clinic:hospitalization:read",
  "clinic:hospitalization:admit",
  "clinic:hospitalization:add_note",
  "clinic:hospitalization:discharge",
  "clinic:hospitalization:export",
  "clinic:lab:read",
  "clinic:lab:order",
  "clinic:lab:collect_sample",
  "clinic:lab:enter_result",
  "clinic:lab:amend",
  "clinic:lab:export",
  "clinic:imaging:read",
  "clinic:imaging:order",
  "clinic:imaging:perform",
  "clinic:imaging:report",
  "clinic:imaging:amend",
  "clinic:imaging:export",
  "clinic:stock:read",
  "clinic:stock:receive",
  "clinic:stock:decrement",
  "clinic:stock:adjust",
  "clinic:stock:export",
  "petshop:config:read",
  "petshop:config:update",
  "petshop:product:read",
  "petshop:product:create",
  "petshop:product:update",
  "petshop:product:archive",
  "petshop:product:export",
  "catalog:product:read",
  "catalog:product:create",
  "catalog:product:update",
  "catalog:product:archive",
  "catalog:product:export",
  "inventory:warehouse:read",
  "inventory:warehouse:create",
  "inventory:warehouse:update",
  "inventory:warehouse:archive",
  "inventory:shelf:read",
  "inventory:shelf:create",
  "inventory:shelf:update",
  "inventory:shelf:archive",
  "inventory:lot:read",
  "inventory:lot:create",
  "inventory:lot:update",
  "inventory:lot:archive",
  "inventory:purchase_order:read",
  "inventory:purchase_order:create",
  "inventory:purchase_order:update",
  "inventory:purchase_order:approve",
  "inventory:purchase_order:receive",
  "inventory:purchase_order:cancel",
  "inventory:stock_movement:read",
  "inventory:stock_movement:create",
  "inventory:stock_movement:reverse",
  "inventory:stock_movement:export",
  "inventory:clinical_consumption:read",
  "inventory:clinical_consumption:create",
  "inventory:clinical_consumption:cancel",
  "inventory:clinical_consumption:export",
  "inventory:stock_alert:read",
  "inventory:stock_alert:acknowledge",
  "inventory:stock_alert:export",
  "catalog:supplier:read",
  "catalog:supplier:create",
  "catalog:supplier:update",
  "catalog:supplier:archive",
  "petshop:stock:read",
  "petshop:stock:receive",
  "petshop:stock:decrement",
  "petshop:stock:adjust",
  "petshop:stock:export",
  "petshop:sale:read",
  "petshop:sale:create",
  "petshop:sale:refund",
  "petshop:sale:export",
  "clinic:payment:read",
  "clinic:payment:create",
  "clinic:payment:reverse",
  "petshop:payment:read",
  "petshop:payment:create",
  "petshop:payment:reverse",
  "cash:read",
  "cash:close",
  "portal:animal:read",
  "portal:vaccination:read",
  "portal:lab:read",
  "portal:imaging:read",
  "portal:payment:read",
  "portal:profile:update",
  "portal:consent:sign",
  "portal:appointment:request",
  "clinic:report:financial:read",
  "clinic:report:clinical:read",
  "clinic:report:stock:read",
  "clinic:report:export",
  "audit:log:read",
  "audit:log:export",
  "file:file:upload",
  "file:file:read",
  "file:file:delete",
  "auth:session:read",
  "auth:session:revoke",
  "auth:password:change",
  "auth:invitation:create",
  "auth:invitation:read",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export type PermissionList = ReadonlyArray<Permission>;

export function isPermission(value: string): value is Permission {
  return (PERMISSIONS as ReadonlyArray<string>).includes(value);
}
