-- Faz 7: append-only tahsilat, ters kayıt ve kasa defteri.
CREATE TABLE payments (id VARCHAR(100) PRIMARY KEY, tenant_id UUID NOT NULL, source_type VARCHAR(50) NOT NULL, source_id VARCHAR(100) NOT NULL, amount NUMERIC(18,4) NOT NULL, method VARCHAR(30) NOT NULL, currency VARCHAR(10) NOT NULL, paid_at TIMESTAMPTZ(6) NOT NULL, idempotency_key VARCHAR(200), reference VARCHAR(300), notes TEXT, status VARCHAR(30) NOT NULL, reversed_amount NUMERIC(18,4) NOT NULL, effective_amount NUMERIC(18,4) NOT NULL, reversed_at TIMESTAMPTZ(6), reversed_by VARCHAR(100), reverse_reason TEXT, created_at TIMESTAMPTZ(6) NOT NULL, created_by VARCHAR(100) NOT NULL);
CREATE UNIQUE INDEX payments_tenant_idempotency_unique ON payments(tenant_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX payments_tenant_source_paid_idx ON payments(tenant_id,source_type,source_id,paid_at);
CREATE TABLE payment_reversals (id VARCHAR(100) PRIMARY KEY, tenant_id UUID NOT NULL, payment_id VARCHAR(100) NOT NULL REFERENCES payments(id) ON DELETE RESTRICT, source_type VARCHAR(50) NOT NULL, source_id VARCHAR(100) NOT NULL, amount NUMERIC(18,4) NOT NULL, method VARCHAR(30) NOT NULL, currency VARCHAR(10) NOT NULL, reason VARCHAR(50) NOT NULL, note TEXT, cash_register_effect BOOLEAN NOT NULL, reversed_at TIMESTAMPTZ(6) NOT NULL, reversed_by VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ(6) NOT NULL);
CREATE INDEX payment_reversals_tenant_payment_idx ON payment_reversals(tenant_id,payment_id,reversed_at);
CREATE INDEX payment_reversals_tenant_source_idx ON payment_reversals(tenant_id,source_type,source_id,reversed_at);
CREATE TABLE kasa_entries (id VARCHAR(100) PRIMARY KEY, tenant_id UUID NOT NULL, account VARCHAR(30) NOT NULL, amount_signed NUMERIC(18,4) NOT NULL, direction VARCHAR(10) NOT NULL, source VARCHAR(50) NOT NULL, reference_id VARCHAR(100) NOT NULL, reference_type VARCHAR(30) NOT NULL, method VARCHAR(30) NOT NULL, currency VARCHAR(10) NOT NULL, occurred_at TIMESTAMPTZ(6) NOT NULL, actor_id VARCHAR(100) NOT NULL, note TEXT);
CREATE INDEX kasa_entries_tenant_account_occurred_idx ON kasa_entries(tenant_id,account,occurred_at);
CREATE INDEX kasa_entries_tenant_reference_idx ON kasa_entries(tenant_id,reference_type,reference_id);
ALTER TABLE payments ENABLE ROW LEVEL SECURITY; ALTER TABLE payment_reversals ENABLE ROW LEVEL SECURITY; ALTER TABLE kasa_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY payments_tenant_isolation ON payments USING (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true)) WITH CHECK (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true));
CREATE POLICY payment_reversals_tenant_isolation ON payment_reversals USING (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true)) WITH CHECK (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true));
CREATE POLICY kasa_entries_tenant_isolation ON kasa_entries USING (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true)) WITH CHECK (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true));
