-- Faz 5: aşı protokolü, uygulama, hatırlatma ve portal kartı ayarları.
CREATE TABLE vaccine_protocols (id VARCHAR(100) PRIMARY KEY, tenant_id UUID NOT NULL, name VARCHAR(300) NOT NULL, species VARCHAR(30) NOT NULL, category VARCHAR(30) NOT NULL, manufacturer VARCHAR(300), default_dose JSONB, steps JSONB NOT NULL, total_duration_months INT NOT NULL, is_core BOOLEAN NOT NULL, created_at TIMESTAMPTZ(6) NOT NULL, created_by VARCHAR(100), updated_at TIMESTAMPTZ(6) NOT NULL, archived_at TIMESTAMPTZ(6));
CREATE INDEX vaccine_protocols_tenant_species_idx ON vaccine_protocols(tenant_id,species,archived_at);
CREATE TABLE vaccine_applications (id VARCHAR(100) PRIMARY KEY, tenant_id UUID NOT NULL, patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE RESTRICT, protocol_id VARCHAR(100) NOT NULL REFERENCES vaccine_protocols(id) ON DELETE RESTRICT, lot JSONB NOT NULL, dose JSONB, administered_by VARCHAR(100) NOT NULL, application_date TIMESTAMPTZ(6) NOT NULL, next_due_date VARCHAR(30), notes TEXT, status VARCHAR(30) NOT NULL, created_at TIMESTAMPTZ(6) NOT NULL, created_by VARCHAR(100) NOT NULL, updated_at TIMESTAMPTZ(6) NOT NULL, amended_at TIMESTAMPTZ(6), amended_by VARCHAR(100), amended_reason TEXT, cancelled_at TIMESTAMPTZ(6), cancellation_reason TEXT, stock_movement_ids JSONB NOT NULL);
CREATE INDEX vaccine_applications_tenant_patient_idx ON vaccine_applications(tenant_id,patient_id,application_date);
CREATE INDEX vaccine_applications_tenant_protocol_idx ON vaccine_applications(tenant_id,protocol_id,application_date);
CREATE TABLE vaccine_reminders (id VARCHAR(100) PRIMARY KEY, tenant_id UUID NOT NULL, application_id VARCHAR(100) NOT NULL, patient_id UUID NOT NULL, protocol_id VARCHAR(100) NOT NULL, channel VARCHAR(30) NOT NULL, scheduled_for TIMESTAMPTZ(6) NOT NULL, next_due_date VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, attempts INT NOT NULL, last_error TEXT, sent_at TIMESTAMPTZ(6), created_at TIMESTAMPTZ(6) NOT NULL, dedupe_key VARCHAR(300) NOT NULL, application_snapshot JSONB, step_snapshot JSONB, UNIQUE(tenant_id,dedupe_key));
CREATE INDEX vaccine_reminders_tenant_status_scheduled_idx ON vaccine_reminders(tenant_id,status,scheduled_for);
CREATE TABLE tenant_vaccine_card_settings (tenant_id UUID PRIMARY KEY, portal_vaccine_card_enabled BOOLEAN NOT NULL, updated_at TIMESTAMPTZ(6) NOT NULL);
ALTER TABLE vaccine_protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE vaccine_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE vaccine_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_vaccine_card_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY vaccine_protocols_tenant_isolation ON vaccine_protocols USING (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true)) WITH CHECK (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true));
CREATE POLICY vaccine_applications_tenant_isolation ON vaccine_applications USING (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true)) WITH CHECK (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true));
CREATE POLICY vaccine_reminders_tenant_isolation ON vaccine_reminders USING (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true)) WITH CHECK (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true));
CREATE POLICY tenant_vaccine_card_settings_tenant_isolation ON tenant_vaccine_card_settings USING (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true)) WITH CHECK (current_setting('app.is_superadmin',true)='true' OR tenant_id::text=current_setting('app.tenant_id',true));
