// Auto-generated by @vetniva/load-test (GOAL-122).
// Senaryo: stock_query — Stok sorgusu
// Profil: smoke (Tek VU, 30sn — saglik kontrolu)
// Bu dosya elle degistirilmemelidir; ureticiden gelir.

import { vetGet, check, jitterSleep, maskString, resolveDeep, resolvePath } from './shared.js';

export const options = {
  stages: [
    { duration: '5s', target: 1 },     // warm-up
    { duration: '30s', target: 1 }, // sustained
    { duration: '5s', target: 0 },                    // cool-down
  ],
  thresholds: {
    // k6 tarafinda hizli baseline; detayli kontrol TypeScript
    // tarafinda (evaluateScenario) yapilir.
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<2000'],
  },
  tags: { suite: 'vetniva-load-test' },
};

export default async function () {
  // step 1: list_products
  const res0 = vetGet(
    resolvePath("/api/v1/catalog/products?limit=50"),
    undefined,
  );
  check(res0, {
    'list_products_status_200': (r) => r.status === 200,
    // Yetkili API cevabi PII icerebilir; test istemcisi bu cevabi tanisal
    // ciktilara yazmadan once maskeler. Bu kontrol maskeleme sozlesmesini
    // dogrular, yetkili kullaniciya gosterilen veriyi "sizinti" saymaz.
    'list_products_diagnostic_body_masked': (r) => !/[\\w.+-]+@[\\w-]+\\.[\\w.-]+|\\b[5-9]\\d{9}[0-9]\\b|\\b0?5\\d{9}\\b/.test(maskString(typeof r.body === 'string' ? r.body : '')),
  });
  jitterSleep(50, 200);


  // step 2: list_stock
  const res1 = vetGet(
    resolvePath("/api/v1/inventory/stock-movements/balances?limit=50"),
    undefined,
  );
  check(res1, {
    'list_stock_status_200': (r) => r.status === 200,
    // Yetkili API cevabi PII icerebilir; test istemcisi bu cevabi tanisal
    // ciktilara yazmadan once maskeler. Bu kontrol maskeleme sozlesmesini
    // dogrular, yetkili kullaniciya gosterilen veriyi "sizinti" saymaz.
    'list_stock_diagnostic_body_masked': (r) => !/[\\w.+-]+@[\\w-]+\\.[\\w.-]+|\\b[5-9]\\d{9}[0-9]\\b|\\b0?5\\d{9}\\b/.test(maskString(typeof r.body === 'string' ? r.body : '')),
  });
  jitterSleep(50, 200);

}
