/**
 * @file Tüm UI etiketleri tek dosyada.
 * @module @vetniva/web/lib/labels
 * @description Layout, header, sidebar, dashboard, login, vb. Tüm
 * kullanıcıya görünen metinler burada toplanır. Çok dilli (tr-TR,
 * en-GB) desteklenir; eksik anahtarlar `tr-TR` fallback'ine düşer.
 *
 * Not: Server component'lerden direkt kullanılabilir; client
 * component'ler `useTranslation` ile erişir. Bu dosya sabit (build
 * time) metinler içindir; çalışma zamanı çevirisi `@vetniva/i18n`
 * üzerinden yapılır.
 */

const tr = {
  brand: {
    name: "VetNiva",
    tagline: "Veteriner klinik yönetim sistemi",
  },
  nav: {
    dashboard: "Anasayfa",
    patients: "Hastalar",
    appointments: "Randevular",
    consultation: "Muayene",
    vaccinations: "Aşılar",
    petshop: "Petshop",
    finance: "Finans",
    settings: "Ayarlar",
    signOut: "Çıkış",
  },
  topbar: {
    search: "Ara…",
    notifications: "Bildirimler",
    noNotifications: "Yeni bildirim yok",
    profile: "Profilim",
    switchLocale: "Dil",
    openMenu: "Menüyü aç",
    closeMenu: "Menüyü kapat",
  },
  login: {
    title: "Hesabınıza giriş yapın",
    subtitle: "Klinik yönetim sistemi",
    emailLabel: "E-posta",
    emailPlaceholder: "ornek@klinik.com",
    passwordLabel: "Şifre",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Şifrenizi mi unuttunuz?",
    submit: "Giriş Yap",
    submitPending: "Giriş yapılıyor…",
    or: "veya",
    portalEntry: "Portal Girişi",
    portalHelp: "Hasta sahibi misiniz?",
    error: {
      invalid: "E-posta veya şifre hatalı.",
      required: "Lütfen e-posta ve şifrenizi girin.",
      generic: "Giriş yapılamadı. Lütfen tekrar deneyin.",
    },
    footer: "© 2026 VetNiva",
  },
  dashboard: {
    greetingMorning: "Günaydın",
    greetingAfternoon: "İyi günler",
    greetingEvening: "İyi akşamlar",
    todayLabel: "Bugün",
    kpi: {
      appointmentsToday: "Bugünkü Randevular",
      waitingPatients: "Bekleyen Hastalar",
      stockAlert: "Stok Uyarısı",
      revenueToday: "Bugünkü Tahsilat",
    },
    sections: {
      todayAppointments: "Bugünkü Randevular",
      quickActions: "Hızlı İşlemler",
      systemStatus: "Sistem Durumu",
    },
    quickActions: {
      newOwner: "Yeni Hasta Sahibi",
      newPatient: "Yeni Hayvan",
      newAppointment: "Yeni Randevu",
      newSale: "Yeni Satış",
    },
    appointmentStatus: {
      waiting: "Beklemede",
      inProgress: "Muayenede",
      completed: "Tamamlandı",
      cancelled: "İptal",
    },
    reason: {
      vaccination: "Aşı kontrolü",
      checkup: "Genel muayene",
      followup: "Kontrol",
      vaccinationBoosters: "Aşı tekrarı",
    },
    empty: {
      noAppointments: "Bugün için randevu yok",
      noAppointmentsHelp: "Yeni bir randevu oluşturarak başlayabilirsiniz.",
    },
  },
  health: {
    title: "Sistem Sağlığı",
    description: "Platform bileşenlerinin canlı durumu.",
    ok: "Çalışıyor",
    degraded: "Kısmen çalışıyor",
    down: "Çalışmıyor",
    db: "Veritabanı",
    latency: "Gecikme",
    correlation: "Correlation ID",
    errorTitle: "Sağlık bilgisi alınamadı",
    noData: "Şu an görüntülenecek veri yok.",
    fetchError:
      "API bağlantısı kurulamadı. Lütfen API servisinin çalıştığından emin olun.",
  },
  system: {
    api: "API",
    database: "Veritabanı",
    queue: "Kuyruk",
    storage: "Depolama",
    version: "Sürüm",
    build: "Build",
    detail: "Detaylar",
  },
  days: {
    mon: "Pzt",
    tue: "Sal",
    wed: "Çar",
    thu: "Per",
    fri: "Cum",
    sat: "Cmt",
    sun: "Paz",
  },
  months: {
    jan: "Oca",
    feb: "Şub",
    mar: "Mar",
    apr: "Nis",
    may: "May",
    jun: "Haz",
    jul: "Tem",
    aug: "Ağu",
    sep: "Eyl",
    oct: "Eki",
    nov: "Kas",
    dec: "Ara",
  },
  units: {
    ms: "ms",
    currency: "₺",
    percent: "%",
  },
  status: {
    up: "Çalışıyor",
    down: "Çalışmıyor",
    unknown: "Bilinmiyor",
  },
  errors: {
    title: "Bir sorun oluştu",
    description:
      "Beklenmeyen bir hatayla karşılaşıldı. Lütfen tekrar deneyin veya destek ekibine bildirin.",
    retry: "Yeniden dene",
  },
  common: {
    save: "Kaydet",
    cancel: "Vazgeç",
    delete: "Sil",
    edit: "Düzenle",
    create: "Oluştur",
    search: "Ara",
    loading: "Yükleniyor…",
    empty: "Kayıt bulunamadı",
    error: "Bir hata oluştu",
    retry: "Tekrar dene",
    back: "Geri",
    next: "İleri",
    previous: "Önceki",
    yes: "Evet",
    no: "Hayır",
    required: "Zorunlu alan",
  },
  onboarding: {
    welcome: "VetNiva Hoş Geldiniz",
    description: "Rolünüzü seçin; ilk adımlarda sizi yönlendirelim.",
    step1Title: "Hoş Geldiniz",
    step1Subtitle: "Rol seçimi",
    step1RoleVet: "Veteriner Hekim",
    step1RoleStaff: "Klinik Personeli",
    step1RoleOwner: "İşletme Sahibi",
    step1RolePortal: "Hasta Sahibi",
    step2Title: "Konu Eşleştir",
    step2Subtitle: "Soru sorun veya senaryo seçin",
    step2InputLabel: "Sorunuz",
    step2InputPlaceholder: "Örn. Aşı kaydı nasıl yapılır?",
    step2Submit: "Yönlendir",
    step3Title: "Adımlar",
    step3Subtitle: "Aşağıdaki adımları takip edin",
    step3NoMatch: "Sorunuzla eşleşen bir senaryo bulunamadı.",
    step3MedicalRefusal:
      "Bu asistan tıbbi sorularda (tanı, tedavi, doz) yardımcı olamaz. Lütfen veteriner hekiminize danışın.",
    step3Navigate: "Sayfaya git",
    ctaStart: "Başla",
    ctaNext: "İleri",
    ctaBack: "Geri",
    ctaFinish: "Bitir",
    ctaClose: "Kapat",
    helpButton: "Yardım",
    empty: "Senaryo bulunamadı",
    loading: "Senaryolar yükleniyor...",
    errorGeneric: "Onboarding içeriği yüklenemedi.",
  },
  // ---------------------------------------------------------------------------
  // SUPERADMIN panel (Faz 10) — ortak namespace
  // Her alt alan (errorCenter / jobRuns / securityEvents / retention) kendi
  // paralel task'ı tarafından genişletilir; burada yalnız shell ve dashboard
  // için gereken anahtarlar foundation tick'inde tanımlanır.
  // ---------------------------------------------------------------------------
  superadmin: {
    brand: "Süper Yönetim",
    tagline: "Operasyonel yönetim konsolu",
    user: "Süper Admin",
    nav: {
      overview: "Genel Bakış",
      errorCenter: "Hata Merkezi",
      jobRuns: "Job Runs",
      securityEvents: "Güvenlik Olayları",
      retention: "Log Saklama",
    },
    kpi: {
      totalErrors24h: "24s Hata Olayı",
      deadLetterLast24h: "24s Dead-Letter",
      securityEventsLast24h: "24s Güvenlik Olayı",
    },
    status: {
      loading: "Yükleniyor…",
      unauthorized: "Bu alana erişim yetkiniz yok.",
      backToDashboard: "Dashboard'a dön",
    },
    breadcrumb: {
      root: "Süper Yönetim",
    },
  },
  // Hata merkezi namespace'i — Tick 1C (Error Center zenginleştirme) tarafından genişletildi
  errorCenter: {
    title: "Hata Merkezi",
    description:
      "Kalıcı hata olaylarını, fingerprint gruplarını ve çözüm durumlarını yönetin.",
    kpi: {
      title: "24 saat özeti",
      total: "Toplam hata (24s)",
      critical: "Kritik (24s)",
      investigating: "İnceleniyor",
      reopened: "Yeniden açıldı",
      loadErrorHint: "Yüklenemedi",
    },
    tabs: {
      list: "Liste",
      groups: "Gruplar (fingerprint)",
    },
    groups: {
      title: "Fingerprint grupları",
      loading: "Gruplar yükleniyor…",
      empty: "Eşleşen fingerprint grubu yok.",
      loadFailed: "Fingerprint grupları yüklenemedi.",
      detailTitle: "Grup detayı",
      detailLoading: "Grup detayı yükleniyor…",
      detailLoadFailed: "Grup detayı yüklenemedi.",
      detailClose: "Detayı kapat",
      columns: {
        fingerprint: "Fingerprint",
        severity: "Şiddet",
        module: "Modül",
        errorCode: "Hata kodu",
        status: "Durum",
        assigned: "Atanan",
        events: "Olay",
        uniqueTenants: "Tenant",
        firstSeen: "İlk görülme",
        lastSeen: "Son görülme",
      },
    },
    filters: {
      status: "Durum",
      severity: "Şiddet",
      search: "Ara",
      tenant: "Tenant",
      branch: "Şube",
      module: "Modül",
      errorCode: "Hata kodu",
      release: "Release",
      assignedTo: "Atanan",
      from: "Başlangıç",
      to: "Bitiş",
      searchPlaceholder: "Kod, mesaj veya modül",
      all: "Tümü",
    },
    statusLabels: {
      new: "Yeni",
      investigating: "İnceleniyor",
      resolved: "Çözüldü",
      reopened: "Yeniden açıldı",
    },
    severityLabels: {
      critical: "Kritik",
      error: "Hata",
      warning: "Uyarı",
      info: "Bilgi",
    },
    table: {
      status: "Durum",
      severity: "Şiddet",
      code: "Kod",
      module: "Modül",
      occurrence: "Tekrar",
      lastSeen: "Son görülme",
    },
    empty: {
      title: "Eşleşen hata olayı yok",
    },
    errorLoad: "Hata kayıtları şu anda yüklenemiyor.",
    errorRetry: "Listeyi yeniden yükle",
    retry: "Yeniden dene",
    totalLabel: "Toplam {count} olay",
    detail: {
      title: "Hata ayrıntısı",
      code: "Kod",
      module: "Modül",
      fingerprint: "Fingerprint",
      occurrence: "Tekrar",
      firstSeen: "İlk / son görülme",
      lastSeen: "İlk / son görülme",
      release: "Release",
      route: "Route",
      message: "Mesaj",
      loading: "Yükleniyor…",
      errorLoad: "Hata ayrıntısı şu anda yüklenemiyor.",
      notFound: "Hata olayı bulunamadı.",
      changeStatus: "Durum",
      saveStatus: "Durumu kaydet",
      statusUpdateError: "Durum güncellenemedi; geçiş kuralını kontrol edin.",
      assignment: {
        title: "Sorumlu atama",
        current: "Mevcut atama",
        unassigned: "Atanmamış",
        userId: "Superadmin kullanıcı kimliği",
        note: "Atama notu",
        assign: "Ata",
        unassign: "Atamayı kaldır",
        updateError: "Hata ataması güncellenemedi.",
      },
      notes: {
        title: "Çözüm notları",
        add: "Yeni not",
        placeholder: "Not içeriği",
        addButton: "Not ekle",
        saveError: "Çözüm notu kaydedilemedi.",
        visibility: {
          internal: "internal",
          shared: "shared",
        },
      },
      support: {
        title: "Destek bağlantısı",
        url: "URL",
        titleField: "Başlık",
        addButton: "Bağlantı ekle",
        saveError: "Destek bağlantısı kaydedilemedi.",
        linkText: "Bağlantı",
      },
      audit: {
        title: "Audit timeline",
        empty: "Bu olay için henüz audit kaydı yok.",
        actionLabels: {
          status_transition: "Durum geçişi",
          note_added: "Not eklendi",
          support_link_added: "Destek bağlantısı eklendi",
          assignment_changed: "Atama değişti",
          occurrence_recorded: "Yeni oluşum kaydedildi",
        },
        reasonSeparator: " — ",
        fromToSeparator: " → ",
        visibilityLabel: "Görünürlük:",
        systemLabel: "Sistem:",
        unassignedLabel: "Atama kaldırıldı",
        assigneeLabel: "Atanan:",
        actorSystem: "Sistem",
      },
    },
  },
  // Job runs namespace'i — FAZ-10 SUPERADMIN job runs modülü
  jobRuns: {
    title: "Job Runs",
    description:
      "Background job ve entegrasyon logları; retry ve dead-letter yönetimi.",
    listHeading: "Job run listesi",
    summaryHeading: "Job runs 24 saat özeti",
    detailHeading: "Job run detayı",
    attemptsHeading: "Aynı jobKey için tüm denemeler",
    deadLetterHeading: "Dead-letter görünümü",
    loadErrorHint: "Job run kayıtları şu anda yüklenemiyor.",
    detailLoadErrorHint: "Job run ayrıntısı şu anda yüklenemiyor.",
    empty: "Filtrelere uyan job run yok.",
    totalLabel: "Toplam {count} job run",
    paginationLabel: "limit=50 · offset=0",
    backToList: "Listeye dön",
    refresh: "Yenile",
    filters: {
      title: "Filtreler",
      queueName: "Queue",
      jobName: "Job adı",
      jobKey: "Job anahtarı",
      status: "Durum",
      source: "Kaynak",
      triggeredBy: "Tetikleyici",
      tenant: "Tenant",
      branch: "Şube",
      country: "Ülke",
      from: "Başlangıç tarihi",
      to: "Bitiş tarihi",
      search: "Ara",
      searchPlaceholder: "jobKey, jobName veya errorCode",
      reset: "Filtreleri sıfırla",
      all: "Tümü",
      deadLetterOnly: "Yalnız dead-letter",
    },
    statuses: {
      pending: "Beklemede",
      running: "Çalışıyor",
      succeeded: "Başarılı",
      failed: "Hata",
      dead_letter: "Dead-Letter",
    },
    sources: {
      queue: "Queue",
      adapter: "Adapter",
      cron: "Cron",
      system: "Sistem",
    },
    triggeredBy: {
      user: "Kullanıcı",
      system: "Sistem",
      schedule: "Zamanlayıcı",
      retry: "Retry",
    },
    columns: {
      status: "Durum",
      queueName: "Queue",
      jobName: "Job",
      attempt: "Deneme",
      source: "Kaynak",
      triggeredBy: "Tetikleyici",
      tenant: "Tenant",
      branch: "Şube",
      country: "Ülke",
      startedAt: "Başlangıç",
      finishedAt: "Bitiş",
      durationMs: "Süre",
      errorCode: "Hata kodu",
      jobKey: "Job anahtarı",
    },
    summary: {
      total: "Toplam",
      succeeded: "Başarılı",
      failed: "Hata",
      deadLetter: "Dead-Letter",
      running: "Çalışıyor",
      pending: "Beklemede",
      last24hDeadLetter: "24s Dead-Letter",
      oldestRunning: "En eski çalışan",
      oldestRunningNone: "Çalışan job yok",
      loadErrorHint: "Yüklenemedi",
    },
    detail: {
      status: "Durum",
      jobKey: "Job anahtarı",
      queueName: "Queue",
      jobName: "Job adı",
      attempt: "Deneme",
      maxAttempts: "Maks. deneme",
      source: "Kaynak",
      triggeredBy: "Tetikleyici",
      triggeredByUser: "Tetikleyen kullanıcı",
      tenant: "Tenant",
      branch: "Şube",
      country: "Ülke",
      startedAt: "Başlangıç",
      finishedAt: "Bitiş",
      durationMs: "Süre",
      errorCode: "Hata kodu",
      correlationId: "Correlation ID",
      input: "Input",
      output: "Output",
      errorStack: "Stack trace",
      noInput: "Input kaydedilmemiş.",
      noOutput: "Output kaydedilmemiş.",
      noErrorStack: "Bu run için stack trace saklanmıyor (başarılı veya terminal).",
      noUser: "Sistem",
      actionsHeading: "Aksiyonlar",
    },
    actions: {
      retry: "Yeniden dene",
      finish: "Run'ı sonlandır",
      viewAttempts: "Tüm denemeleri gör",
      viewDetail: "Detayı aç",
      retrySuccess: "Job run yeniden kuyruğa alındı.",
      retryError: "Job run yeniden denenemedi.",
      finishSuccess: "Job run sonlandırıldı.",
      finishError: "Job run sonlandırılamadı.",
    },
    attempts: {
      listHeading: "Tüm denemeler",
      loadErrorHint: "Denemeler yüklenemedi.",
      empty: "Bu jobKey için ek deneme yok.",
      totalLabel: "Toplam {count} deneme",
    },
  },
  // Güvenlik olayları namespace'i — SUPERADMIN Security Events modülü (FAZ-10)
  securityEvents: {
    title: "Güvenlik Olayları",
    description:
      "Kimlik doğrulama, yetki ve tenant izolasyon alarmlarını SUPERADMIN panelinden izleyin.",
    listHeading: "Güvenlik Olayı Listesi",
    summaryHeading: "Özet Görünüm",
    empty: "Eşleşen güvenlik olayı bulunamadı.",
    loadErrorHint: "Yüklenemedi",
    totalLabel: "Toplam {count} olay",
    filters: {
      type: "Tür",
      severity: "Şiddet",
      module: "Modül",
      tenant: "Tenant",
      branch: "Şube",
      user: "Kullanıcı",
      country: "Ülke",
      release: "Sürüm",
      route: "Route",
      from: "Başlangıç",
      to: "Bitiş",
      search: "Ara",
      reset: "Filtreleri temizle",
    },
    types: {
      failed_login: "Başarısız Giriş",
      unauthorized_access_attempt: "Yetkisiz Erişim Denemesi",
      suspicious_export: "Şüpheli Dışa Aktarım",
      role_change: "Rol Değişikliği",
      tenant_isolation_breach_attempt: "Tenant İzolasyon İhlali Denemesi",
    },
    severities: {
      info: "Bilgi",
      warning: "Uyarı",
      error: "Hata",
      critical: "Kritik",
    },
    table: {
      type: "Tür",
      severity: "Şiddet",
      module: "Modül",
      code: "Kod",
      message: "Mesaj",
      route: "Route",
      country: "Ülke",
      occurrence: "Tekrar",
      lastSeen: "Son Görülme",
      alertSent: "Alarm",
    },
    summary: {
      title: "Severity × Tür Kırılımı",
      topGroupsTitle: "En Çok Tekrarlanan Saldırı Sınıfları",
      topGroupsHint: "Top-20 fingerprint; eventCount DESC sıralı.",
      noTopGroups: "Öne çıkan saldırı sınıfı bulunamadı.",
      eventCountLabel: "{count} olay",
    },
    detail: {
      heading: "Güvenlik Olayı Detayı",
      backToList: "Listeye dön",
      typeLabel: "Tür",
      severityLabel: "Şiddet",
      moduleLabel: "Modül",
      errorCodeLabel: "Hata Kodu",
      messageLabel: "Mesaj",
      statusCodeLabel: "HTTP Durum Kodu",
      fingerprintLabel: "Fingerprint",
      requestIdLabel: "Request ID",
      maskedIpLabel: "Mask'li IP",
      userAgentHashLabel: "User Agent Hash",
      countryLabel: "Ülke",
      routeLabel: "Route",
      releaseLabel: "Sürüm",
      occurrenceCountLabel: "Tekrar Sayısı",
      firstSeenLabel: "İlk Görülme",
      lastSeenLabel: "Son Görülme",
      alertSentLabel: "Alarm Gönderildi",
      alertSentYes: "Evet",
      alertSentNo: "Hayır",
      contextLabel: "PII-Mask'lı Bağlam",
      noContext: "Bağlam bilgisi yok.",
      loadError: "Güvenlik olayı detayı şu anda yüklenemiyor.",
      notFound: "Güvenlik olayı bulunamadı; ID yanlış veya silinmiş olabilir.",
    },
  },
  // ---------------------------------------------------------------------------
  // Log Saklama (FAZ-10, GOAL-105) — retention policies + sweeps + effective
  // ---------------------------------------------------------------------------
  retention: {
    title: "Log Saklama",
    description:
      "Tenant × logType × severity retention politikaları ve süpürme geçmişi.",
    tabs: {
      policies: "Politikalar",
      sweeps: "Sweep Geçmişi",
      effective: "Effective",
    },
    filters: {
      title: "Filtreler",
      tenant: "Tenant",
      tenantPlaceholder: "Tümü (global dahil)",
      logType: "Log Tipi",
      severity: "Şiddet",
      from: "Başlangıç",
      to: "Bitiş",
      all: "Tümü",
      global: "Global",
      any: "Tümü",
    },
    logType: {
      audit_log: "Audit Log",
      error_event: "Hata Olayı",
      security_event: "Güvenlik Olayı",
      job_run: "Job Run",
      notification: "Bildirim",
      request_log: "İstek Log",
    },
    severity: {
      info: "Bilgi",
      warning: "Uyarı",
      error: "Hata",
      critical: "Kritik",
    },
    archiveStorage: {
      hot: "Hot (Canlı DB)",
      cold: "Cold (Object Storage)",
      none: "Yok (Yalnız Sil)",
    },
    policy: {
      id: "ID",
      tenant: "Tenant",
      logType: "Log Tipi",
      severity: "Şiddet",
      retentionDays: "Saklama (gün)",
      archiveAfterDays: "Arşiv (gün)",
      archiveStorage: "Arşiv Depolama",
      redactPii: "PII Maskeleme",
      createdBy: "Oluşturan",
      createdAt: "Oluşturulma",
      updatedBy: "Güncelleyen",
      updatedAt: "Güncellenme",
      globalBadge: "Global",
    },
    sweep: {
      id: "ID",
      runAt: "Çalıştırma",
      startedAt: "Başlangıç",
      finishedAt: "Bitiş",
      duration: "Süre",
      dryRun: "Kuru Çalışma",
      triggeredBy: "Tetikleyen",
      bucket: "Bucket",
      tenant: "Tenant",
      logType: "Log Tipi",
      severity: "Şiddet",
      cutoff: "Cutoff",
      expired: "Süresi Dolan",
      archived: "Arşivlenen",
      deleted: "Silinen",
      totals: "Toplam",
      status: "Durum",
      error: "Hata",
    },
    effective: {
      title: "Effective Policy Önizleme",
      description:
        "Tenant × logType × severity kombinasyonu için geçerli policy'nin hangi kaynaktan geldiğini gösterir.",
      source: "Kaynak",
      sourceTenantOverride: "Tenant Override",
      sourceGlobalOverride: "Global Override",
      sourceDefault: "Default",
      apply: "Hesapla",
      noResult: "Önizleme için filtreleri doldurun.",
    },
    form: {
      titleNew: "Yeni Policy",
      titleEdit: "Policy Düzenle",
      tenantLabel: "Tenant (boş = global override)",
      tenantPlaceholder: "UUID veya boş bırakın",
      tenantHint: "Boş bırakılırsa global override oluşturulur.",
      logTypeLabel: "Log Tipi",
      severityLabel: "Şiddet",
      retentionDaysLabel: "Saklama (gün, 1-3650)",
      archiveAfterDaysLabel: "Arşiv (gün, 0 - retentionDays)",
      archiveStorageLabel: "Arşiv Depolama",
      redactPiiLabel: "PII Maskeleme (her zaman true)",
      submitCreate: "Oluştur",
      submitSave: "Kaydet",
      cancel: "Vazgeç",
      validation: {
        retentionRange: "Saklama 1-3650 arası olmalı.",
        archiveRange: "Arşiv, retention değerinden büyük olamaz.",
        required: "Tüm alanlar zorunludur.",
      },
    },
    common: {
      empty: "Kayıt bulunamadı",
      loading: "Yükleniyor…",
      error: "Veri yüklenemedi",
      loadErrorHint: "Yeniden deneyin veya API bağlantısını kontrol edin.",
      saveSuccess: "Kayıt güncellendi.",
      saveError: "Kayıt güncellenemedi.",
      delete: "Sil",
      deleteSuccess: "Kayıt silindi.",
      deleteError: "Kayıt silinemedi.",
      deleteConfirm: "Bu policy'yi silmek istediğinize emin misiniz?",
      dryRun: "Kuru çalışma",
      runSweep: "Sweep Başlat",
      newPolicy: "Yeni Policy",
      newSweep: "Sweep Başlat",
      modalAria: "Modal diyalog",
      close: "Kapat",
      back: "Listeye dön",
      detail: "Detay",
    },
    modal: {
      sweepTitle: "Manuel Retention Sweep",
      sweepDescription:
        "Effective policy çözümü ile tüm tenant × logType × severity bucket'ları üzerinde sweep çalıştırır.",
      dryRunLabel: "Dry-run (yalnız sayım)",
      logTypesLabel: "Log Tipleri (boş = hepsi)",
      tenantLabel: "Tenant (boş = global)",
      tenantPlaceholder: "UUID veya boş",
      submit: "Sweep Başlat",
    },
  },
} as const;

const en = {
  brand: {
    name: "VetNiva",
    tagline: "Veterinary clinic management platform",
  },
  nav: {
    dashboard: "Dashboard",
    patients: "Patients",
    appointments: "Appointments",
    consultation: "Consultation",
    vaccinations: "Vaccinations",
    petshop: "Petshop",
    finance: "Finance",
    settings: "Settings",
    signOut: "Sign out",
  },
  topbar: {
    search: "Search…",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    profile: "My profile",
    switchLocale: "Language",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  login: {
    title: "Sign in to your account",
    subtitle: "Clinic management system",
    emailLabel: "Email",
    emailPlaceholder: "you@clinic.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Forgot password?",
    submit: "Sign in",
    submitPending: "Signing in…",
    or: "or",
    portalEntry: "Portal sign in",
    portalHelp: "Are you a pet owner?",
    error: {
      invalid: "Invalid email or password.",
      required: "Please enter your email and password.",
      generic: "Could not sign in. Please try again.",
    },
    footer: "© 2026 VetNiva",
  },
  dashboard: {
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    todayLabel: "Today",
    kpi: {
      appointmentsToday: "Today's appointments",
      waitingPatients: "Waiting patients",
      stockAlert: "Stock alerts",
      revenueToday: "Today's revenue",
    },
    sections: {
      todayAppointments: "Today's appointments",
      quickActions: "Quick actions",
      systemStatus: "System status",
    },
    quickActions: {
      newOwner: "New owner",
      newPatient: "New patient",
      newAppointment: "New appointment",
      newSale: "New sale",
    },
    appointmentStatus: {
      waiting: "Waiting",
      inProgress: "In progress",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    reason: {
      vaccination: "Vaccination check",
      checkup: "General checkup",
      followup: "Follow-up",
      vaccinationBoosters: "Booster shot",
    },
    empty: {
      noAppointments: "No appointments today",
      noAppointmentsHelp: "Get started by creating a new appointment.",
    },
  },
  health: {
    title: "System health",
    description: "Live status of platform components.",
    ok: "Operational",
    degraded: "Degraded",
    down: "Down",
    db: "Database",
    latency: "Latency",
    correlation: "Correlation ID",
    errorTitle: "Health information unavailable",
    noData: "No data to display right now.",
    fetchError:
      "Could not reach the API. Please ensure the API service is running.",
  },
  system: {
    api: "API",
    database: "Database",
    queue: "Queue",
    storage: "Storage",
    version: "Version",
    build: "Build",
    detail: "Details",
  },
  days: {
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
  },
  months: {
    jan: "Jan",
    feb: "Feb",
    mar: "Mar",
    apr: "Apr",
    may: "May",
    jun: "Jun",
    jul: "Jul",
    aug: "Aug",
    sep: "Sep",
    oct: "Oct",
    nov: "Nov",
    dec: "Dec",
  },
  units: {
    ms: "ms",
    currency: "₺",
    percent: "%",
  },
  status: {
    up: "Operational",
    down: "Down",
    unknown: "Unknown",
  },
  errors: {
    title: "Something went wrong",
    description:
      "An unexpected error occurred. Please try again or contact support.",
    retry: "Try again",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    search: "Search",
    loading: "Loading…",
    empty: "No records found",
    error: "An error occurred",
    retry: "Try again",
    back: "Back",
    next: "Next",
    previous: "Previous",
    yes: "Yes",
    no: "No",
    required: "Required",
  },
  onboarding: {
    welcome: "Welcome to VetNiva",
    description: "Pick your role to personalise the guidance.",
    step1Title: "Welcome",
    step1Subtitle: "Pick your role",
    step1RoleVet: "Veterinarian",
    step1RoleStaff: "Clinic staff",
    step1RoleOwner: "Clinic owner",
    step1RolePortal: "Pet owner (portal)",
    step2Title: "Match a topic",
    step2Subtitle: "Ask a question or pick a scenario",
    step2InputLabel: "Your question",
    step2InputPlaceholder: "e.g. How do I record a vaccination?",
    step2Submit: "Find guidance",
    step3Title: "Steps",
    step3Subtitle: "Follow the steps below",
    step3NoMatch: "No scenario matched your question.",
    step3MedicalRefusal:
      "This assistant cannot help with medical questions (diagnosis, treatment, dosage). Please consult your veterinarian.",
    step3Navigate: "Go to page",
    ctaStart: "Start",
    ctaNext: "Next",
    ctaBack: "Back",
    ctaFinish: "Finish",
    ctaClose: "Close",
    helpButton: "Help",
    empty: "No scenarios available",
    loading: "Loading scenarios...",
    errorGeneric: "Could not load onboarding content.",
  },
  // ---------------------------------------------------------------------------
  // SUPERADMIN panel (Faz 10) — common namespace
  // ---------------------------------------------------------------------------
  superadmin: {
    brand: "Super Admin",
    tagline: "Operational management console",
    user: "Super Admin",
    nav: {
      overview: "Overview",
      errorCenter: "Error Center",
      jobRuns: "Job Runs",
      securityEvents: "Security Events",
      retention: "Log Retention",
    },
    kpi: {
      totalErrors24h: "Errors (24h)",
      deadLetterLast24h: "Dead-letter (24h)",
      securityEventsLast24h: "Security events (24h)",
    },
    status: {
      loading: "Loading…",
      unauthorized: "You do not have access to this area.",
      backToDashboard: "Back to dashboard",
    },
    breadcrumb: {
      root: "Super Admin",
    },
  },
  errorCenter: {
    title: "Error Center",
    description:
      "Manage persistent error events, fingerprint groups and resolution status.",
    kpi: {
      title: "24 hour summary",
      total: "Total errors (24h)",
      critical: "Critical (24h)",
      investigating: "Investigating",
      reopened: "Reopened",
      loadErrorHint: "Unavailable",
    },
    tabs: {
      list: "List",
      groups: "Groups (fingerprint)",
    },
    groups: {
      title: "Fingerprint groups",
      loading: "Loading groups…",
      empty: "No matching fingerprint groups.",
      loadFailed: "Could not load fingerprint groups.",
      detailTitle: "Group detail",
      detailLoading: "Loading group detail…",
      detailLoadFailed: "Could not load group detail.",
      detailClose: "Close detail",
      columns: {
        fingerprint: "Fingerprint",
        severity: "Severity",
        module: "Module",
        errorCode: "Error code",
        status: "Status",
        assigned: "Assigned",
        events: "Events",
        uniqueTenants: "Tenants",
        firstSeen: "First seen",
        lastSeen: "Last seen",
      },
    },
    filters: {
      status: "Status",
      severity: "Severity",
      search: "Search",
      tenant: "Tenant",
      branch: "Branch",
      module: "Module",
      errorCode: "Error code",
      release: "Release",
      assignedTo: "Assigned to",
      from: "From",
      to: "To",
      searchPlaceholder: "Code, message, or module",
      all: "All",
    },
    statusLabels: {
      new: "New",
      investigating: "Investigating",
      resolved: "Resolved",
      reopened: "Reopened",
    },
    severityLabels: {
      critical: "Critical",
      error: "Error",
      warning: "Warning",
      info: "Info",
    },
    table: {
      status: "Status",
      severity: "Severity",
      code: "Code",
      module: "Module",
      occurrence: "Occurrences",
      lastSeen: "Last seen",
    },
    empty: {
      title: "No matching error events",
    },
    errorLoad: "Error records could not be loaded at this time.",
    errorRetry: "Reload list",
    retry: "Retry",
    totalLabel: "{count} events total",
    detail: {
      title: "Error detail",
      code: "Code",
      module: "Module",
      fingerprint: "Fingerprint",
      occurrence: "Occurrences",
      firstSeen: "First / last seen",
      lastSeen: "First / last seen",
      release: "Release",
      route: "Route",
      message: "Message",
      loading: "Loading…",
      errorLoad: "Error detail could not be loaded at this time.",
      notFound: "Error event not found.",
      changeStatus: "Status",
      saveStatus: "Save status",
      statusUpdateError: "Status could not be updated; verify the transition rule.",
      assignment: {
        title: "Assignee",
        current: "Current assignee",
        unassigned: "Unassigned",
        userId: "Superadmin user id",
        note: "Assignment note",
        assign: "Assign",
        unassign: "Unassign",
        updateError: "Assignment could not be updated.",
      },
      notes: {
        title: "Resolution notes",
        add: "New note",
        placeholder: "Note body",
        addButton: "Add note",
        saveError: "Resolution note could not be saved.",
        visibility: {
          internal: "internal",
          shared: "shared",
        },
      },
      support: {
        title: "Support link",
        url: "URL",
        titleField: "Title",
        addButton: "Add link",
        saveError: "Support link could not be saved.",
        linkText: "Link",
      },
      audit: {
        title: "Audit timeline",
        empty: "No audit entries for this event yet.",
        actionLabels: {
          status_transition: "Status transition",
          note_added: "Note added",
          support_link_added: "Support link added",
          assignment_changed: "Assignment changed",
          occurrence_recorded: "New occurrence recorded",
        },
        reasonSeparator: " — ",
        fromToSeparator: " → ",
        visibilityLabel: "Visibility:",
        systemLabel: "System:",
        unassignedLabel: "Assignment removed",
        assigneeLabel: "Assignee:",
        actorSystem: "System",
      },
    },
  },
  jobRuns: {
    title: "Job Runs",
    description:
      "Background job and integration logs; retry and dead-letter management.",
    listHeading: "Job run list",
    summaryHeading: "Job runs 24h summary",
    detailHeading: "Job run detail",
    attemptsHeading: "All attempts for this jobKey",
    deadLetterHeading: "Dead-letter view",
    loadErrorHint: "Job run records could not be loaded at this time.",
    detailLoadErrorHint: "Job run detail could not be loaded at this time.",
    empty: "No job runs match the current filters.",
    totalLabel: "Total {count} job runs",
    paginationLabel: "limit=50 · offset=0",
    backToList: "Back to list",
    refresh: "Refresh",
    filters: {
      title: "Filters",
      queueName: "Queue",
      jobName: "Job name",
      jobKey: "Job key",
      status: "Status",
      source: "Source",
      triggeredBy: "Triggered by",
      tenant: "Tenant",
      branch: "Branch",
      country: "Country",
      from: "From date",
      to: "To date",
      search: "Search",
      searchPlaceholder: "jobKey, jobName, or errorCode",
      reset: "Reset filters",
      all: "All",
      deadLetterOnly: "Dead-letter only",
    },
    statuses: {
      pending: "Pending",
      running: "Running",
      succeeded: "Succeeded",
      failed: "Failed",
      dead_letter: "Dead-Letter",
    },
    sources: {
      queue: "Queue",
      adapter: "Adapter",
      cron: "Cron",
      system: "System",
    },
    triggeredBy: {
      user: "User",
      system: "System",
      schedule: "Scheduler",
      retry: "Retry",
    },
    columns: {
      status: "Status",
      queueName: "Queue",
      jobName: "Job",
      attempt: "Attempt",
      source: "Source",
      triggeredBy: "Triggered by",
      tenant: "Tenant",
      branch: "Branch",
      country: "Country",
      startedAt: "Started",
      finishedAt: "Finished",
      durationMs: "Duration",
      errorCode: "Error code",
      jobKey: "Job key",
    },
    summary: {
      total: "Total",
      succeeded: "Succeeded",
      failed: "Failed",
      deadLetter: "Dead-Letter",
      running: "Running",
      pending: "Pending",
      last24hDeadLetter: "Dead-letter (24h)",
      oldestRunning: "Oldest running",
      oldestRunningNone: "No running jobs",
      loadErrorHint: "Could not load",
    },
    detail: {
      status: "Status",
      jobKey: "Job key",
      queueName: "Queue",
      jobName: "Job name",
      attempt: "Attempt",
      maxAttempts: "Max. attempts",
      source: "Source",
      triggeredBy: "Triggered by",
      triggeredByUser: "Triggered by user",
      tenant: "Tenant",
      branch: "Branch",
      country: "Country",
      startedAt: "Started",
      finishedAt: "Finished",
      durationMs: "Duration",
      errorCode: "Error code",
      correlationId: "Correlation ID",
      input: "Input",
      output: "Output",
      errorStack: "Stack trace",
      noInput: "No input recorded.",
      noOutput: "No output recorded.",
      noErrorStack: "No stack trace is stored for this run (successful or terminal).",
      noUser: "System",
      actionsHeading: "Actions",
    },
    actions: {
      retry: "Retry",
      finish: "Finish run",
      viewAttempts: "View all attempts",
      viewDetail: "View detail",
      retrySuccess: "Job run was re-queued.",
      retryError: "Job run could not be retried.",
      finishSuccess: "Job run was finished.",
      finishError: "Job run could not be finished.",
    },
    attempts: {
      listHeading: "All attempts",
      loadErrorHint: "Attempts could not be loaded.",
      empty: "No additional attempts for this jobKey.",
      totalLabel: "Total {count} attempts",
    },
  },
  securityEvents: {
    title: "Security Events",
    description:
      "Monitor authentication, authorization and tenant isolation alerts from the SUPERADMIN panel.",
    listHeading: "Security Event List",
    summaryHeading: "Summary View",
    empty: "No matching security events found.",
    loadErrorHint: "Could not load",
    totalLabel: "{count} events total",
    filters: {
      type: "Type",
      severity: "Severity",
      module: "Module",
      tenant: "Tenant",
      branch: "Branch",
      user: "User",
      country: "Country",
      release: "Release",
      route: "Route",
      from: "From",
      to: "To",
      search: "Search",
      reset: "Clear filters",
    },
    types: {
      failed_login: "Failed Login",
      unauthorized_access_attempt: "Unauthorized Access Attempt",
      suspicious_export: "Suspicious Export",
      role_change: "Role Change",
      tenant_isolation_breach_attempt: "Tenant Isolation Breach Attempt",
    },
    severities: {
      info: "Info",
      warning: "Warning",
      error: "Error",
      critical: "Critical",
    },
    table: {
      type: "Type",
      severity: "Severity",
      module: "Module",
      code: "Code",
      message: "Message",
      route: "Route",
      country: "Country",
      occurrence: "Occurrences",
      lastSeen: "Last Seen",
      alertSent: "Alert",
    },
    summary: {
      title: "Severity × Type Breakdown",
      topGroupsTitle: "Top Recurring Attack Classes",
      topGroupsHint: "Top-20 fingerprints, sorted by eventCount DESC.",
      noTopGroups: "No prominent attack classes found.",
      eventCountLabel: "{count} events",
    },
    detail: {
      heading: "Security Event Detail",
      backToList: "Back to list",
      typeLabel: "Type",
      severityLabel: "Severity",
      moduleLabel: "Module",
      errorCodeLabel: "Error Code",
      messageLabel: "Message",
      statusCodeLabel: "HTTP Status Code",
      fingerprintLabel: "Fingerprint",
      requestIdLabel: "Request ID",
      maskedIpLabel: "Masked IP",
      userAgentHashLabel: "User Agent Hash",
      countryLabel: "Country",
      routeLabel: "Route",
      releaseLabel: "Release",
      occurrenceCountLabel: "Occurrence Count",
      firstSeenLabel: "First Seen",
      lastSeenLabel: "Last Seen",
      alertSentLabel: "Alert Sent",
      alertSentYes: "Yes",
      alertSentNo: "No",
      contextLabel: "PII-Masked Context",
      noContext: "No context information.",
      loadError: "Could not load security event details.",
      notFound: "Security event not found; ID may be wrong or deleted.",
    },
  },
  retention: {
    title: "Log Retention",
    description:
      "Tenant × logType × severity retention policies and sweep history.",
    tabs: {
      policies: "Policies",
      sweeps: "Sweep History",
      effective: "Effective",
    },
    filters: {
      title: "Filters",
      tenant: "Tenant",
      tenantPlaceholder: "All (including global)",
      logType: "Log Type",
      severity: "Severity",
      from: "From",
      to: "To",
      all: "All",
      global: "Global",
      any: "Any",
    },
    logType: {
      audit_log: "Audit Log",
      error_event: "Error Event",
      security_event: "Security Event",
      job_run: "Job Run",
      notification: "Notification",
      request_log: "Request Log",
    },
    severity: {
      info: "Info",
      warning: "Warning",
      error: "Error",
      critical: "Critical",
    },
    archiveStorage: {
      hot: "Hot (live DB)",
      cold: "Cold (object storage)",
      none: "None (delete only)",
    },
    policy: {
      id: "ID",
      tenant: "Tenant",
      logType: "Log Type",
      severity: "Severity",
      retentionDays: "Retention (days)",
      archiveAfterDays: "Archive (days)",
      archiveStorage: "Archive Storage",
      redactPii: "PII Redaction",
      createdBy: "Created by",
      createdAt: "Created at",
      updatedBy: "Updated by",
      updatedAt: "Updated at",
      globalBadge: "Global",
    },
    sweep: {
      id: "ID",
      runAt: "Run at",
      startedAt: "Started",
      finishedAt: "Finished",
      duration: "Duration",
      dryRun: "Dry Run",
      triggeredBy: "Triggered by",
      bucket: "Bucket",
      tenant: "Tenant",
      logType: "Log Type",
      severity: "Severity",
      cutoff: "Cutoff",
      expired: "Expired",
      archived: "Archived",
      deleted: "Deleted",
      totals: "Totals",
      status: "Status",
      error: "Error",
    },
    effective: {
      title: "Effective Policy Preview",
      description:
        "Shows which source the resolved policy comes from for a tenant × logType × severity combination.",
      source: "Source",
      sourceTenantOverride: "Tenant override",
      sourceGlobalOverride: "Global override",
      sourceDefault: "Default",
      apply: "Resolve",
      noResult: "Fill in the filters to preview.",
    },
    form: {
      titleNew: "New Policy",
      titleEdit: "Edit Policy",
      tenantLabel: "Tenant (empty = global override)",
      tenantPlaceholder: "UUID or leave empty",
      tenantHint: "Leave empty to create a global override.",
      logTypeLabel: "Log Type",
      severityLabel: "Severity",
      retentionDaysLabel: "Retention (days, 1-3650)",
      archiveAfterDaysLabel: "Archive (days, 0 - retentionDays)",
      archiveStorageLabel: "Archive Storage",
      redactPiiLabel: "PII Redaction (always true)",
      submitCreate: "Create",
      submitSave: "Save",
      cancel: "Cancel",
      validation: {
        retentionRange: "Retention must be between 1 and 3650.",
        archiveRange: "Archive must not exceed retention.",
        required: "All fields are required.",
      },
    },
    common: {
      empty: "No records found",
      loading: "Loading…",
      error: "Could not load data",
      loadErrorHint: "Try again or check the API connection.",
      saveSuccess: "Record updated.",
      saveError: "Could not save the record.",
      delete: "Delete",
      deleteSuccess: "Record deleted.",
      deleteError: "Could not delete the record.",
      deleteConfirm: "Are you sure you want to delete this policy?",
      dryRun: "Dry run",
      runSweep: "Start Sweep",
      newPolicy: "New Policy",
      newSweep: "Start Sweep",
      modalAria: "Modal dialog",
      close: "Close",
      back: "Back to list",
      detail: "Detail",
    },
    modal: {
      sweepTitle: "Manual Retention Sweep",
      sweepDescription:
        "Runs a sweep across all tenant × logType × severity buckets using the resolved effective policy.",
      dryRunLabel: "Dry-run (count only)",
      logTypesLabel: "Log Types (empty = all)",
      tenantLabel: "Tenant (empty = global)",
      tenantPlaceholder: "UUID or empty",
      submit: "Start Sweep",
    },
  },
} as const;

export type Labels = typeof tr;
export type Locale = "tr-TR" | "en-GB";

const dictionaries: Record<Locale, Labels> = {
  "tr-TR": tr,
  // İngilizce sözlük, Türkçe ile aynı yapısal tipte (literal
  // değerler farklı, tipler `string`'e genişletilmiş).
  "en-GB": en as unknown as Labels,
};

/**
 * Aktif locale için etiket setini döner. Bilinmeyen bir değer gelirse
 * varsayılan olarak `tr-TR` kullanılır.
 * @param locale
 */
export function getLabels(locale: string | null | undefined): Labels {
  if (locale === "en-GB") return dictionaries["en-GB"];
  return dictionaries["tr-TR"];
}

/**
 * Belirli bir anahtar yolunu (`nav.dashboard` gibi) döner. Sunucu
 * tarafında doğrudan erişim için tip güvenli yardımcı.
 * @param labels
 * @param key
 */
export function label<L extends Labels, K extends keyof L>(
  labels: L,
  key: K,
): L[K] {
  // Anahtar generic `keyof L` ile derleme zamanında sınırlandırılmıştır.
  // eslint-disable-next-line security/detect-object-injection
  return labels[key];
}
