/**
 * @file k6 script uretici.
 * @module @vetniva/load-test/generator
 *
 * @description ScenarioConfig listesinden k6 .js senaryo
 * scriptlerini uretir. Tenant izolasyonu, PII mask ve audit
 * gereksinimlerine uyar. Uretilen scriptler src/k6/ altinda
 * tutulur; el ile duzenlenmemelidir.
 *
 * @since GOAL-122 (FAZ-12) performans ve yuk testi
 */

import { writeFile, mkdir, readdir } from "node:fs/promises";
import { join, dirname } from "node:path";

import { K6_SHARED_TEMPLATE, k6Options } from "./k6-shared.js";
import { PROFILE_SHAPES, resolveStages } from "./config.js";
import type { LoadProfile, ScenarioConfig, ScenarioStep } from "./types.js";

/** Uretilen k6 dosyasinin govdesini olusturur. */
function renderScenarioScript(
  scenario: ScenarioConfig,
  profile: LoadProfile,
): string {
  const header = `// Auto-generated by @vetniva/load-test (GOAL-122).
// Senaryo: ${scenario.key} — ${scenario.title}
// Profil: ${profile} (${PROFILE_SHAPES[profile].description})
// Bu dosya elle degistirilmemelidir; ureticiden gelir.
`;

  const importLine = `import { ${joinImports(scenario)}, maskString, resolveDeep, resolvePath } from './shared.js';`;

  const stages = resolveStages(scenario, profile);
  const options = k6Options(PROFILE_SHAPES[profile], stages);

  const body = scenario.steps
    .map((step, idx) => renderStep(step, idx))
    .join("\n\n");

  return `${header}\n${importLine}\n\n${options}\nexport default async function () {\n${body}\n}\n`;
}

/** ScenarioStep listesinden import isimlerini uretir. */
function joinImports(scenario: ScenarioConfig): string {
  const needed = new Set<string>();
  for (const step of scenario.steps) {
    const verb = step.method.toLowerCase();
    if (verb === "get") needed.add("vetGet");
    else if (verb === "post") needed.add("vetPost");
    else if (verb === "put") needed.add("vetPut");
    else if (verb === "patch") needed.add("vetPatch");
    else if (verb === "delete") needed.add("vetDelete");
  }
  needed.add("check");
  needed.add("jitterSleep");
  return Array.from(needed).join(", ");
}

/** Tek bir step'i k6 koda cevirir. */
function renderStep(step: ScenarioStep, idx: number): string {
  const fn = `vet${step.method.charAt(0)}${step.method.slice(1).toLowerCase()}`;
  const bodyLiteral =
    step.body === undefined
      ? "undefined"
      : `resolveDeep(${JSON.stringify(step.body, null, 2)})`;
  const pathLiteral = `resolvePath(${JSON.stringify(step.path)})`;
  const expectStatus = step.method === "POST" ? 201 : 200;
  return `  // step ${idx + 1}: ${step.name}
  const res${idx} = ${fn}(
    ${pathLiteral},
    ${bodyLiteral},
  );
  check(res${idx}, {
    '${step.name}_status_${expectStatus}': (r) => r.status === ${expectStatus},
    // Yetkili API cevabi PII icerebilir; test istemcisi bu cevabi tanisal
    // ciktilara yazmadan once maskeler. Bu kontrol maskeleme sozlesmesini
    // dogrular, yetkili kullaniciya gosterilen veriyi "sizinti" saymaz.
    '${step.name}_diagnostic_body_masked': (r) => !/${"$"}{PI_BODY_REGEX}/.test(maskString(typeof r.body === 'string' ? r.body : '')),
  });
  jitterSleep(50, 200);
`;
}

/** PII body regex (k6 tarafi). */
const PI_BODY_REGEX =
  "[\\\\w.+-]+@[\\\\w-]+\\\\.[\\\\w.-]+|\\\\b[5-9]\\\\d{9}[0-9]\\\\b|\\\\b0?5\\\\d{9}\\\\b";

/** Senaryo + profil icin k6 script metnini uretir. */
export function generateScenarioScript(
  scenario: ScenarioConfig,
  profile: LoadProfile,
): string {
  // PI_BODY_REGEX'i string olarak inline etmek icin replace yapalim.
  return renderScenarioScript(scenario, profile).replace(
    /\$\{PI_BODY_REGEX\}/g,
    PI_BODY_REGEX,
  );
}

/** Tum senaryolar + profil icin k6 dosyalarini diske yazar. */
export async function writeAllScripts(
  outDir: string,
  profile: LoadProfile,
  scenarios: ReadonlyArray<ScenarioConfig>,
): Promise<ReadonlyArray<{ file: string; key: string }>> {
  await mkdir(outDir, { recursive: true });
  // shared.js her zaman yeniden yazilir
  await writeFile(join(outDir, "shared.js"), K6_SHARED_TEMPLATE, "utf8");

  const written: { file: string; key: string }[] = [];
  for (const s of scenarios) {
    const file = join(outDir, `${s.key}.js`);
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, generateScenarioScript(s, profile), "utf8");
    written.push({ file, key: s.key });
  }
  return written;
}

/** Dizindeki .js dosyalarini listeler (test/dogrulama icin). */
export async function listJsFiles(dir: string): Promise<ReadonlyArray<string>> {
  try {
    const entries = await readdir(dir);
    return entries.filter((e) => e.endsWith(".js")).sort();
  } catch {
    return [];
  }
}
