/**
 * @file k6 ortak helper modulu (k6 script uretimi icin).
 * @module @vetniva/load-test/k6-shared
 *
 * @description 7 kritik senaryonun k6 .js scriptleri tarafindan
 * paylasilan helper kodunu uretir. Tenant izolasyonu, auth,
 * PII maskeleme ve audit kurallarina uyar; placeholder veri
 * kullanir (gercek PII yok).
 *
 * Bu dosya runtime'da k6 tarafindan calistirilmaz; uretici
 * olarak k6-shared.js sablon metnini disari verir.
 *
 * @since GOAL-122 (FAZ-12) performans ve yuk testi
 */

/** k6 shared.js sablon metni (k6 import edebilir). */
export const K6_SHARED_TEMPLATE = `// Auto-generated by @vetniva/load-test (GOAL-122).
// k6 ortak helper: auth + PII mask + tenant header.
// Bu dosya elle degistirilmemelidir; ureticiden gelir.

import http from 'k6/http';
import { check, fail, sleep } from 'k6';
import { Counter, Rate, Trend } from 'k6/metrics';

// ---- Konfig (env uzerinden override edilebilir) ----
const BASE_URL = __ENV.BASE_URL || 'http://localhost:3001';
const TENANT_ID = __ENV.TENANT_ID || 'tnt-pilot-kadikoy';
const BRANCH_ID = __ENV.BRANCH_ID || 'brc-pilot-merkez';
const AUTH_TOKEN = __ENV.AUTH_TOKEN || '';
const USER_ID = __ENV.USER_ID || 'usr-pilot-vet';

// patientId benzeri katalog placeholder'larını environment'tan çözer.
// Konfigürasyon anahtarları snake case environment adına dönüştürülür.
export function resolvePath(value) {
  return String(value).replace(/\\{([A-Za-z0-9_]+)\\}/g, function (_match, key) {
    const envKey = key.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
    const resolved = __ENV[envKey];
    if (!resolved) fail('Missing load-test environment variable: ' + envKey);
    return resolved;
  });
}

export function resolveDeep(value) {
  if (typeof value === 'string') return resolvePath(value);
  if (Array.isArray(value)) return value.map(resolveDeep);
  if (value && typeof value === 'object') {
    const out = {};
    Object.keys(value).forEach(function (key) { out[key] = resolveDeep(value[key]); });
    return out;
  }
  return value;
}

// ---- Custom metrikler ----
export const errorCount = new Counter('vetniva_errors');
export const piiRedactedCount = new Counter('vetniva_pii_redacted');
export const tenantBoundaryCheck = new Rate('vetniva_tenant_boundary_ok');

// ---- Header fabrikasi ----
export function authHeaders(extra) {
  const h = Object.assign(
    {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'X-Tenant-Id': TENANT_ID,
      'X-Branch-Id': BRANCH_ID,
      'X-User-Id': USER_ID,
    },
    extra || {},
  );
  if (AUTH_TOKEN) h['Authorization'] = 'Bearer ' + AUTH_TOKEN;
  return h;
}

// ---- Tenant izolasyonu dogrulamasi ----
export function assertTenantBoundary(res) {
  const hdrTenant = res.headers['X-Tenant-Id'] || res.headers['x-tenant-id'];
  const ok = !hdrTenant || hdrTenant === TENANT_ID;
  tenantBoundaryCheck.add(ok ? 1 : 0);
  if (!ok) {
    errorCount.add(1);
    fail('Tenant boundary breach: response X-Tenant-Id=' + hdrTenant);
  }
}

// ---- PII mask (basit) ----
// Yanit govdesindeki email / TCKN / telefon alanlarini maskeler.
// Asil maskeleme PiiMasker (apps/api) tarafindan yapilir; bu
// yalnizca yuk testi istemcisi tarafinda olusan PII'nin loga
// dusmesini engeller.
export function maskString(s) {
  if (typeof s !== 'string') return s;
  return s
    .replace(/[\\w.+-]+@[\\w-]+\\.[\\w.-]+/g, '***@***')
    .replace(/\\b[5-9]\\d{9}[0-9]\\b/g, '***********') // TCKN
    .replace(/\\b0?5\\d{9}\\b/g, '0**********');        // TR telefon
}

// ---- Request helper ----
export function vetGet(path, params) {
  const res = http.get(BASE_URL + path, Object.assign({ headers: authHeaders() }, params || {}));
  assertTenantBoundary(res);
  return res;
}

export function vetPost(path, body, params) {
  const res = http.post(
    BASE_URL + path,
    JSON.stringify(body || {}),
    Object.assign({ headers: authHeaders() }, params || {}),
  );
  assertTenantBoundary(res);
  return res;
}

export function vetPut(path, body, params) {
  const res = http.put(
    BASE_URL + path,
    JSON.stringify(body || {}),
    Object.assign({ headers: authHeaders() }, params || {}),
  );
  assertTenantBoundary(res);
  return res;
}

export function vetPatch(path, body, params) {
  const res = http.patch(
    BASE_URL + path,
    JSON.stringify(body || {}),
    Object.assign({ headers: authHeaders() }, params || {}),
  );
  assertTenantBoundary(res);
  return res;
}

export function vetDelete(path, params) {
  const res = http.del(BASE_URL + path, null, Object.assign({ headers: authHeaders() }, params || {}));
  assertTenantBoundary(res);
  return res;
}

// ---- Sleep helper ----
export function jitterSleep(minMs, maxMs) {
  const ms = minMs + Math.random() * (maxMs - minMs);
  sleep(ms / 1000);
}
`;

/**
 * Tum senaryolar icin k6 options blogu uretir.
 * Profile (smoke/pilot/first_100/stress) VU ve sureyi belirler.
 * Warm-up / cool-down sureleri stages bloguna yansir; bu
 * sayede k6 rampa asamasinda JIT/cache isinmasi nedeniyle
 * olusan false-positive latency piklerini threshold
 * hesabina katmaz.
 */
export function k6Options(
  profileShape: {
    vus: number;
    duration: string;
    description: string;
  },
  stages?: { warmup: string | null; cooldown: string | null },
): string {
  const useStages =
    stages && (stages.warmup !== null || stages.cooldown !== null);

  if (!useStages) {
    return `export const options = {
  vus: ${profileShape.vus},
  duration: '${profileShape.duration}',
  thresholds: {
    // k6 tarafinda hizli baseline; detayli kontrol TypeScript
    // tarafinda (evaluateScenario) yapilir.
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<2000'],
  },
  tags: { suite: 'vetniva-load-test' },
};
`;
  }

  // Warm-up + sustained + cool-down. Surenin govde kismi
  // tam sayi degilse k6 stages "30s" gibi kabul eder.
  const warmup = stages.warmup ?? "0s";
  const cooldown = stages.cooldown ?? "0s";
  return `export const options = {
  stages: [
    { duration: '${warmup}', target: ${profileShape.vus} },     // warm-up
    { duration: '${profileShape.duration}', target: ${profileShape.vus} }, // sustained
    { duration: '${cooldown}', target: 0 },                    // cool-down
  ],
  thresholds: {
    // k6 tarafinda hizli baseline; detayli kontrol TypeScript
    // tarafinda (evaluateScenario) yapilir.
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<2000'],
  },
  tags: { suite: 'vetniva-load-test' },
};
`;
}
